### ISSUE TITLE
Causes an error when creating grammar.

### ISSUE THREAD

**Issue by leksito** [transceptor-technology/pyleri#10]
I try to create grammar for js (i use code from example) and get the error:
`In [19]: Grammar() export_js()
--> 336         self._element = self.START
    337         self._string = None
    338         self._expecting = None

AttributeError: 'Grammar' object has no attribute 'START'`
What am i doing wrong?

**Comment by joente** [comment]
Probably you are running the export function directly from the Grammar class. The documentation code might be a bit confusing but it should be something like this:
```python
class MyGrammar(Grammar):
    r_name = Regex('(?:"(?:[^"]*)")+')
    k_hi = Keyword('hi')
    START = Sequence(k_hi, r_name)

# Compile your grammar by creating an instance of the Grammar Class.
my_grammar = MyGrammar()

# Run export_js on an instance of the grammar class
my_grammar.export_js()
```
