### ISSUE TITLE
pyleri python runtime module

### ISSUE THREAD

**Issue by bernstei** [transceptor-technology/pyleri#15]
Does anyone have a sense of how much code would be required to be in the subset of pyleri that was used by the _generated_ python code, like a runtime library for the generated parsers?  We are thinking of contributing some code that uses a pyleri-generated parser to another project, and it would be nice to minimize the amount of accessory code we'd have to include or make them install.  Would such a pyleri python runtime module even be a significant savings?  Also, how much work would it be to extract, but if it's not likely to be a substantially smaller codebase, it's probably not even worth thinking about that aspect.

**Comment by joente** [comment]
@bernstei , technically this is certainly possible (and probably not very difficult), but the code base of pyleri is already small, so I don't think it's worth spending time to make it even smaller. Note that pyleri has no dependencies at all, so you don't have to worry about that either.

**Comment by bernstei** [comment]
OK - we expected that, but we just thought we'd check.  Thanks for taking the time to consider it and answer.
