### ISSUE TITLE
wrong double-quote token string in C output

### ISSUE THREAD

**Issue by bernstei** [transceptor-technology/pyleri#16]
If you define a grammar with a double-quote `"` token and try to produce C output, the string it produces is `"""`, rather than `"\""`, which confuses the C compiler.  If you run the python script in the attached zip file it will produce the corresponding grammar C source (also attached), which reproduces the issue on lines 25 and 27.

[quote_bug_grammar.zip](https://github.com/transceptor-technology/pyleri/files/5623251/quote_bug_grammar.zip)

**Comment by bernstei** [comment]
One way to fix this would be to replace the line in the token.py `_export_c()` definition that writes the quoted string (line 41, I think) with a function that converts the potentially arbitrary string to a valid C string literal, but I don't know where else in the code this functionality might also be useful.

**Comment by joente** [comment]
@bernstei , thanks for finding this issue. It seems to be a problem with any export, not only the export to C. Both `Token` and `Tokens` (and potentially also `Keyword` when such character can be a part of a keyword) are affected.

I've updated the `master` branch with a fix, version `1.3.3-alpha-0` (1.3.3a0), can you test if this solved the issue?

**Comment by bernstei** [comment]
Thanks, I'll take a look.

**Comment by bernstei** [comment]
Yes, indeed, it fixes our problem.  Thanks for the super-quick response.
