### ISSUE TITLE
Creating recursive rules

### ISSUE THREAD

**Issue by owenps** [transceptor-technology/pyleri#20]
Hi pyleri team!

I am interested in defining a recursive rule that follows the following structure

`E ::= Constant | (E + E) | (E - E) | (E * E)`

However, encoding this rule in pyleri using a `Choice` element would require me to reference `E` before `E` is defined. I couldn't find an example in the documentation. Is this possible with the current version or could someone point me in the right direction?

Thanks!
O.

**Comment by joente** [comment]
A little late as the issue is already closed, but here is an example using the "Prio" element to implement the above. I left the "Constant" part out as this is not relevant for the issue. 

```python
from pyleri import Grammar, Sequence, Token, Tokens, Prio, THIS


class Example(Grammar):
    expression = Token('E')  # just a token for the example

    START = Sequence(
        expression,
        Token('::='), Prio(
            expression,
            Sequence('(', THIS, ')'),
            Sequence(THIS, Tokens('| + - *'), THIS)
        )
    )


example = Example()
print(example.parse('E ::= E | (E + E) | (E - E) | (E * E)').is_valid)  # => True
```

**Comment by owenps** [comment]
Hi @joente this looks great! I must have missed `Prio` in the documentation. Thanks for your time 😊
